### ISSUE TITLE
got this error

### ISSUE THREAD

**Issue by myc0sis** [f00d4tehg0dz/kasm-discord-screenshare#1]
+ exec /dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh --wait
/dockerstartup/kasm_default_profile.sh: line 61: /dockerstartup/vnc_startup.sh: Permission denied

**Comment by f00d4tehg0dz** [comment]
> * exec /dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh --wait
>   /dockerstartup/kasm_default_profile.sh: line 61: /dockerstartup/vnc_startup.sh: Permission denied

try `sudo chmod a+x vnc_startup.sh`

looks like I didn't set the permissions properly. I'll fix it on my end and upload it!

**Comment by f00d4tehg0dz** [comment]
> * exec /dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh --wait
>   /dockerstartup/kasm_default_profile.sh: line 61: /dockerstartup/vnc_startup.sh: Permission denied

Hey There!
I've been toying with this and, unfortunately, haven't run into your issue. I uploaded a [short-version.mp4](https://streamable.com/b8g5i2) and a [long-version.mp4](https://streamable.com/titm3m) of the Dockerfile build and Docker run processes. The short version just trimmed the entire build log output. Other than that, they are identical. username: `kasm_user`, password: `password`. For logging into the development Docker run. 

Alternatively, you can just grab the built Docker image [here](https://github.com/f00d4tehg0dz/kasm-discord-screenshare/pkgs/container/kasm-discord-screenshare) or [here] ](https://hub.docker.com/r/f00d4tehg0dz/kasm-discord-screenshare) and spin up a container!

If you still experience issues, I'm happy to hop on a call with you and debug!

**Comment by myc0sis** [comment]
> > * exec /dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh --wait
> >   /dockerstartup/kasm_default_profile.sh: line 61: /dockerstartup/vnc_startup.sh: Permission denied
> 
> Hey There! I've been toying with this and, unfortunately, haven't run into your issue. I uploaded a [short-version.mp4](https://streamable.com/b8g5i2) and a [long-version.mp4](https://streamable.com/titm3m) of the Dockerfile build and Docker run processes. The short version just trimmed the entire build log output. Other than that, they are identical. username: `kasm_user`, password: `password`. For logging into the development Docker run.
> 
> Alternatively, you can just grab the built Docker image [here](https://github.com/f00d4tehg0dz/kasm-discord-screenshare/pkgs/container/kasm-discord-screenshare) or [here] ](https://hub.docker.com/r/f00d4tehg0dz/kasm-discord-screenshare) and spin up a container!
> 
> If you still experience issues, I'm happy to hop on a call with you and debug!

perhaps a discord server in relation to your project? that would be lovely!

**Comment by f00d4tehg0dz** [comment]
> > > * exec /dockerstartup/vnc_startup.sh /dockerstartup/kasm_startup.sh --wait
> > >   /dockerstartup/kasm_default_profile.sh: line 61: /dockerstartup/vnc_startup.sh: Permission denied
> > 
> > 
> > Hey There! I've been toying with this and, unfortunately, haven't run into your issue. I uploaded a [short-version.mp4](https://streamable.com/b8g5i2) and a [long-version.mp4](https://streamable.com/titm3m) of the Dockerfile build and Docker run processes. The short version just trimmed the entire build log output. Other than that, they are identical. username: `kasm_user`, password: `password`. For logging into the development Docker run.
> > Alternatively, you can just grab the built Docker image [here](https://github.com/f00d4tehg0dz/kasm-discord-screenshare/pkgs/container/kasm-discord-screenshare) or [here] ](https://hub.docker.com/r/f00d4tehg0dz/kasm-discord-screenshare) and spin up a container!
> > If you still experience issues, I'm happy to hop on a call with you and debug!
> 
> perhaps a discord server in relation to your project? that would be lovely!

Hey, I definitely haven't forgotten you. Life has unfortunately gotten in the way. Here is an invite to one of my Discord servers for some Discord Bots. We can use this and chat. LMK if you have any time this weekend, I'll be available Friday Evening, Saturday ( all day ) and mostly Sunday! https://discord.gg/PzkGNAs4Ba

**Comment by f00d4tehg0dz** [comment]
Following up as the latest release should have resolved this issue. @myc0sis  let me know when you have a chance to test and see!

**Comment by f00d4tehg0dz** [comment]
closing as this issue may have gone stale
