### ISSUE TITLE
Refactor as a Kasm Workspace Registry?

### ISSUE THREAD

**Issue by codylc** [f00d4tehg0dz/kasm-discord-screenshare#2]
This request may be way off base, but instead of standing up a custom Kasm docker, could this project be refactored to be a 3rd party Kasm Workspace Registry? Seems like the safer, cleaner approach.

https://kasmweb.com/docs/latest/guide/workspace_registry.html

**Comment by f00d4tehg0dz** [comment]
I'm already ahead of you, although I forgot to add it to this repo's readme. :) Let me know if this works for you! 
[Registry]( https://f00d4tehg0dz.github.io/kasm_workspaces/1.0/)

[Github](https://github.com/f00d4tehg0dz/kasm_workspaces)

**Comment by codylc** [comment]
This worked even better than expected! Super easy, thanks for building this!

It feels greedy to ask, but maybe consider including VLC to account for other video streams that aren't natively supported in the browser.

**Comment by f00d4tehg0dz** [comment]
> This worked even better than expected! Super easy, thanks for building this!
> 
> It feels greedy to ask, but maybe consider including VLC to account for other video streams that aren't natively supported in the browser.

Sure thing. I added VLC, desktop shortcut and made the images web browser point to Firefox by default. 

**Info**

- Release pkg: https://github.com/f00d4tehg0dz/kasm-discord-screenshare/releases/tag/1.0.7
- Docker: f00d4tehg0dz/kasm-discord-screenshare:latest
- Docker: f00d4tehg0dz/kasm-discord-screenshare:1.0.7
- Ghcr: ghcr.io/f00d4tehg0dz/kasm-discord-screenshare:latest
- Kasm Workspace Registry: https://f00d4tehg0dz.github.io/kasm_workspaces
- Tagged Kasm Workspace: https://f00d4tehg0dz.github.io/kasm_workspaces/1.12

**Comment by codylc** [comment]
Working great! Had some issues initially getting it to pull the change, but that probably has more to do with my lack of Kasm experience than anything here. Thanks again!!
